version: "3"

tasks:
  default:
    desc: Runs all of the default tasks
    cmds:
      - task: ci

  ci:
    desc: Run all CI tasks
    cmds:
      - task: deps
      - task: unit-test
      - task: lint

  deps:
    desc: Install all dependencies
    cmds:
      - go mod tidy

  test:
    desc: Run all of the tests
    cmds:
      - task: unit-test

  unit-test:
    desc: Run the unit tests
    cmds:
      - go test -update

  lint:
    desc: Lint the code using golangci-lint
    vars:
      REPORT_FORMAT: '{{default "colored-line-number" .REPORT_FORMAT}}'
    cmds:
      - golangci-lint run --timeout 5m0s --out-format {{.REPORT_FORMAT}}

  format:
    desc: Format the code using gofumpt
    cmds:
      - gofumpt -w -l .
